FROM mcr.microsoft.com/dotnet/sdk:9.0
RUN wget https://aka.ms/getvsdbgsh && sh getvsdbgsh -v latest  -l /vsdbg
RUN apt update
RUN apt install -y openssh-client
RUN apt install -y psmisc
RUN apt install -y sudo
